// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3UJ09XF2Z__ZTc9KDCfxGpLjxPV2X234',
    appId: '1:255725654486:web:3a3dce08a6b09b6e391477',
    messagingSenderId: '255725654486',
    projectId: 'flutter-food-application',
    authDomain: 'flutter-food-application.firebaseapp.com',
    storageBucket: 'flutter-food-application.appspot.com',
    measurementId: 'G-H2TX838PV3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvumhhTWxd7DL3e3n8azXdzfPuvnmvS2M',
    appId: '1:255725654486:android:3c610aeb585126ec391477',
    messagingSenderId: '255725654486',
    projectId: 'flutter-food-application',
    storageBucket: 'flutter-food-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmFC35E-3dWASpAl1YdwhTPF3RvXEiWmQ',
    appId: '1:255725654486:ios:072cc42fa32d54b4391477',
    messagingSenderId: '255725654486',
    projectId: 'flutter-food-application',
    storageBucket: 'flutter-food-application.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmFC35E-3dWASpAl1YdwhTPF3RvXEiWmQ',
    appId: '1:255725654486:ios:88711a35569baa5e391477',
    messagingSenderId: '255725654486',
    projectId: 'flutter-food-application',
    storageBucket: 'flutter-food-application.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
